find_package(PkgConfig)
pkg_check_modules(PC_OPENCDM ocdm)

if(PC_OPENCDM_FOUND)
  find_path(OPENCDM_INCLUDE_DIRS
    NAMES open_cdm.h
    HINTS ${PC_OPENCDM_INCLUDEDIR}
    ${PC_OPENCDM_INCLUDE_DIRS}
    PATH_SUFFIXES ocdm
    )

  find_library(OPENCDM_LIBRARIES
    NAMES ocdm
    HINTS ${PC_OPENCDM_LIBDIR}
    ${PC_OPENCDM_LIBRARY_DIRS}
    )
endif()

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(OPENCDM DEFAULT_MSG OPENCDM_LIBRARIES OPENCDM_INCLUDE_DIRS)
mark_as_advanced(OPENCDM_INCLUDE_DIRS OPENCDM_LIBRARIES)
